//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisosaIris27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreventaDetalle
    {
        public int Id { get; set; }
        public Nullable<int> CodigoProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> PreventaId { get; set; }
        public Nullable<int> VendedorId { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Preventa Preventa { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
